In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("weighted_avg_data.csv")
print(df.head())

   hourly_demand_met_mw  apparent_temperature_bhopal  \
0              11116.43                         17.3
1              10713.61                         16.7
2              10211.59                         16.5
3              10310.55                         16.2
4              10470.74                         15.8

   apparent_temperature_gwalior  apparent_temperature_indore  \
0                          10.5                         20.2
1                           9.2                         20.1
2                           9.4                         18.2
3                           8.9                         17.5
4                           8.2                         17.0

   apparent_temperature_jabalpur  apparent_temperature_singrauli  \
0                           16.8                            13.2
1                           16.3                            12.9
2                           14.0                            10.6
3                           13.8                            10.0
4                           13.0                            11.0

   apparent_temperature_ujjain        date  hour  is_holiday  temp_weighted
0                         18.7  2024-01-01     0           0      16.889380
1                         18.0  2024-01-01     1           0      16.389380
2                         17.7  2024-01-01     2           0      15.156637
3                         17.3  2024-01-01     3           0      14.686726
4                         16.9  2024-01-01     4           0      14.317699

In [4]:
print(df.columns)

Index(['hourly_demand_met_mw', 'apparent_temperature_bhopal',
       'apparent_temperature_gwalior', 'apparent_temperature_indore',
       'apparent_temperature_jabalpur', 'apparent_temperature_singrauli',
       'apparent_temperature_ujjain', 'date', 'hour', 'is_holiday',
       'temp_weighted'],
      dtype='object')

In [7]:
print(df.shape)
print(df.dtypes)

(19704, 11)
hourly_demand_met_mw              float64
apparent_temperature_bhopal       float64
apparent_temperature_gwalior      float64
apparent_temperature_indore       float64
apparent_temperature_jabalpur     float64
apparent_temperature_singrauli    float64
apparent_temperature_ujjain       float64
date                               object
hour                                int64
is_holiday                          int64
temp_weighted                     float64
dtype: object

In [9]:
df["temp_weighted"].corr(df["hourly_demand_met_mw"])

-0.14284860897014562

In [10]:
temp_cols = [
    "apparent_temperature_bhopal",
    "apparent_temperature_gwalior",
    "apparent_temperature_indore",
    "apparent_temperature_jabalpur",
    "apparent_temperature_singrauli",
    "apparent_temperature_ujjain"
]

for col in temp_cols:
    print(col,
          df[col].corr(df["hourly_demand_met_mw"]))

apparent_temperature_bhopal -0.12348640001544346
apparent_temperature_gwalior -0.23609139542866536
apparent_temperature_indore -0.082054697430604
apparent_temperature_jabalpur -0.14446067607876265
apparent_temperature_singrauli -0.18999985199831426
apparent_temperature_ujjain -0.10177918423183144

In [11]:
df["date"] = pd.to_datetime(df["date"])

df["month"] = df["date"].dt.month

df.groupby("month")["hourly_demand_met_mw"].mean()

month
1     13456.103687
2     13400.589995
3     12210.188472
4     11354.761667
5     11741.125484
6     10638.085729
7     10075.584630
8     10254.282231
9     10515.903521
10    10412.433488
11    12173.776792
12    13724.567137
Name: hourly_demand_met_mw, dtype: float64

In [12]:
print(df.head())

   hourly_demand_met_mw  apparent_temperature_bhopal  \
0              11116.43                         17.3
1              10713.61                         16.7
2              10211.59                         16.5
3              10310.55                         16.2
4              10470.74                         15.8

   apparent_temperature_gwalior  apparent_temperature_indore  \
0                          10.5                         20.2
1                           9.2                         20.1
2                           9.4                         18.2
3                           8.9                         17.5
4                           8.2                         17.0

   apparent_temperature_jabalpur  apparent_temperature_singrauli  \
0                           16.8                            13.2
1                           16.3                            12.9
2                           14.0                            10.6
3                           13.8                            10.0
4                           13.0                            11.0

   apparent_temperature_ujjain       date  hour  is_holiday  temp_weighted  \
0                         18.7 2024-01-01     0           0      16.889380
1                         18.0 2024-01-01     1           0      16.389380
2                         17.7 2024-01-01     2           0      15.156637
3                         17.3 2024-01-01     3           0      14.686726
4                         16.9 2024-01-01     4           0      14.317699

   month
0      1
1      1
2      1
3      1
4      1

In [28]:
season_df = pd.read_csv("Seasons_Finalized_again.csv")
season_df.head()

                  time  season
0  2024-01-01 00:00:00  Winter
1  2024-01-01 01:00:00  Winter
2  2024-01-01 02:00:00  Winter
3  2024-01-01 03:00:00  Winter
4  2024-01-01 04:00:00  Winter

In [29]:
print(len(df))
print(len(season_df))

19704
19704

In [30]:
df["season"] = season_df["season"]

In [31]:
df[["date", "hour", "season"]].head(10)

        date  hour  season
0 2024-01-01     0  Winter
1 2024-01-01     1  Winter
2 2024-01-01     2  Winter
3 2024-01-01     3  Winter
4 2024-01-01     4  Winter
5 2024-01-01     5  Winter
6 2024-01-01     6  Winter
7 2024-01-01     7  Winter
8 2024-01-01     8  Winter
9 2024-01-01     9  Winter

In [32]:
df.groupby("season")["hourly_demand_met_mw"].mean()

season
Autumn     10463.320389
Monsoon    10164.933431
Summer     11574.793279
Winter     13239.391875
Name: hourly_demand_met_mw, dtype: float64

In [37]:
holiday_df = pd.read_csv("holidays_hourly.csv")
holiday_df.head()

            time  holiday
0  1/1/2024 0:00        1
1  1/1/2024 1:00        1
2  1/1/2024 2:00        1
3  1/1/2024 3:00        1
4  1/1/2024 4:00        1

In [38]:
print(len(df))
print(len(holiday_df))

19704
19704

In [40]:
df["holiday"] = holiday_df["holiday"]
df[["date", "hour", "holiday"]].head(10)

        date  hour  holiday
0 2024-01-01     0        1
1 2024-01-01     1        1
2 2024-01-01     2        1
3 2024-01-01     3        1
4 2024-01-01     4        1
5 2024-01-01     5        1
6 2024-01-01     6        1
7 2024-01-01     7        1
8 2024-01-01     8        1
9 2024-01-01     9        1

In [41]:
df.groupby("holiday")["hourly_demand_met_mw"].mean()

holiday
0    11842.964141
1    11726.938072
Name: hourly_demand_met_mw, dtype: float64

In [43]:
df.groupby("month")[["temp_weighted", "hourly_demand_met_mw"]].mean()

       temp_weighted  hourly_demand_met_mw
month
1          16.712977          13456.103687
2          20.645487          13400.589995
3          25.040337          12210.188472
4          29.846498          11354.761667
5          33.211835          11741.125484
6          33.356249          10638.085729
7          30.807046          10075.584630
8          30.257755          10254.282231
9          30.207542          10515.903521
10         27.919543          10412.433488
11         21.245576          12173.776792
12         17.108362          13724.567137

In [46]:
display(df.corr(numeric_only=True)["hourly_demand_met_mw"])

display(df.groupby("season")["hourly_demand_met_mw"].mean())

display(df.groupby("month")[["temp_weighted","hourly_demand_met_mw"]].mean())

hourly_demand_met_mw              1.000000
apparent_temperature_bhopal      -0.123486
apparent_temperature_gwalior     -0.236091
apparent_temperature_indore      -0.082055
apparent_temperature_jabalpur    -0.144461
apparent_temperature_singrauli   -0.190000
apparent_temperature_ujjain      -0.101779
hour                              0.084641
is_holiday                       -0.017412
temp_weighted                    -0.142849
month                            -0.204376
holiday                          -0.022940
Name: hourly_demand_met_mw, dtype: float64

season
Autumn     10463.320389
Monsoon    10164.933431
Summer     11574.793279
Winter     13239.391875
Name: hourly_demand_met_mw, dtype: float64

       temp_weighted  hourly_demand_met_mw
month
1          16.712977          13456.103687
2          20.645487          13400.589995
3          25.040337          12210.188472
4          29.846498          11354.761667
5          33.211835          11741.125484
6          33.356249          10638.085729
7          30.807046          10075.584630
8          30.257755          10254.282231
9          30.207542          10515.903521
10         27.919543          10412.433488
11         21.245576          12173.776792
12         17.108362          13724.567137

In [ ]:
#hourly demand profile
df.groupby("hour")["hourly_demand_met_mw"].mean()

hour
0     10742.810475
1     10579.104568
2     10300.348575
3     10390.362351
4     10365.543276
5     10404.074689
6     11218.876699
7     12806.868270
8     13250.556382
9     13519.195956
10    13443.342594
11    13343.321486
12    12718.380305
13    12863.725786
14    12651.038831
15    12688.736675
16    12495.696480
17    12366.154823
18    11915.619269
19    11885.613983
20    11234.498234
21    10541.471754
22    10602.901754
23    10990.515773
Name: hourly_demand_met_mw, dtype: float64

In [ ]:
temp_cols = [
    "apparent_temperature_bhopal",
    "apparent_temperature_gwalior",
    "apparent_temperature_indore",
    "apparent_temperature_jabalpur",
    "apparent_temperature_singrauli",
    "apparent_temperature_ujjain"
]

df = df.drop(columns=temp_cols)

KeyError: "['apparent_temperature_bhopal', 'apparent_temperature_gwalior', 'apparent_temperature_indore', 'apparent_temperature_jabalpur', 'apparent_temperature_singrauli', 'apparent_temperature_ujjainis_holiday'] not found in axis"

In [51]:
print(df.columns)

Index(['hourly_demand_met_mw', 'date', 'hour', 'is_holiday', 'temp_weighted',
       'month', 'season', 'holiday'],
      dtype='object')

In [56]:
df = df.drop(columns=["is_holiday"])

KeyError: "['is_holiday'] not found in axis"

In [57]:
df.head()

,hourly_demand_met_mw,date,hour,temp_weighted,month,season,holiday
0,11116.43,2024-01-01,0,16.889380,1,Winter,1
1,10713.61,2024-01-01,1,16.389380,1,Winter,1
2,10211.59,2024-01-01,2,15.156637,1,Winter,1
3,10310.55,2024-01-01,3,14.686726,1,Winter,1
4,10470.74,2024-01-01,4,14.317699,1,Winter,1

In [58]:
df_hourly = df.copy()

In [60]:
#creation of date time index
df_hourly["datetime"] = pd.to_datetime(
    df_hourly["date"].astype(str)
    + " "
    + df_hourly["hour"].astype(str)
    + ":00:00"
)

df_hourly = df_hourly.set_index("datetime")

In [62]:
df_15min = df_hourly.resample("15min").interpolate(
    method="linear"
)

C:\Users\Vanshika\AppData\Local\Temp\ipykernel_6832\2772791403.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_15min = df_hourly.resample("15min").interpolate(

In [63]:
print(df_hourly.shape)

print(df_15min.shape)

(19704, 7)
(78813, 7)

In [64]:
df_hourly.to_csv(
    "mp_hourly_cleaned.csv"
)

df_15min.to_csv(
    "mp_15min_interpolated.csv"
)

In [65]:
df_15min.head()

,hourly_demand_met_mw,date,hour,temp_weighted,month,season,holiday
datetime,,,,,,,
2024-01-01 00:00:00,11116.430,2024-01-01,0.00,16.88938,1.0,Winter,1.0
2024-01-01 00:15:00,11015.725,2024-01-01,0.25,16.76438,1.0,NaN,1.0
2024-01-01 00:30:00,10915.020,2024-01-01,0.50,16.63938,1.0,NaN,1.0
2024-01-01 00:45:00,10814.315,2024-01-01,0.75,16.51438,1.0,NaN,1.0
2024-01-01 01:00:00,10713.610,2024-01-01,1.00,16.38938,1.0,Winter,1.0